fix: rework intrface Joint State on UI
sergei-nntu/orb pull request #138
Opened 2024-06-13 11:16 UTC by Dmitriy8998

2024-06-13 11:50 UTC, Kropanov commented
@Dmitriy8998 You've made a mistake in the title. Please check it!

2024-06-17 07:21 UTC, sw1pr0g requested changes

2024-06-17 07:21 UTC, sw1pr0g commented on web/src/pages/oqp/components/States/JointState.tsx
> +                                            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
need to remove this HARDCODE, please follow eslint recommendations. in this case u need to check if value not number

2024-06-17 07:21 UTC, sw1pr0g commented on web/src/pages/oqp/components/States/JointState.tsx
> +                                            // @ts-expect-error
ignoring these types of errors not correct, it may cause problems in future and incorrect behavior of the application in case of various backend errors

2024-06-17 07:21 UTC, sw1pr0g commented on web/src/pages/oqp/components/States/JointState.tsx
> +                                )}
this is a very redundant iteration of values, please find a universal way to do this, and if you have 1000 values, you will simply get confused!

2024-06-17 07:52 UTC, Kropanov requested changes

2024-06-17 12:27 UTC, Kropanov commented on web/src/pages/oqp/components/States/JointState.tsx
> +                                            // @ts-expect-error
@Dmitriy8998 @sw1pr0g I guess, it's not necessary here. Let's leave it.

2024-06-18 09:56 UTC, Kropanov approved these changes

2024-06-18 09:58 UTC, Kropanov approved these changes

2024-06-18 11:25 UTC, sw1pr0g approved these changes

2024-06-19 12:47 UTC, Kropanov requested changes

2024-06-19 12:47 UTC, Kropanov commented on web/src/pages/oqp/Oqp.tsx
> +    const stateFirstStart = useRef(false);
Rename refs, these names don't make sense

2024-06-19 13:39 UTC, Dmitriy8998 commented
Renamed the refs.  Please see if the name is correct?

2024-06-19 13:49 UTC, Kropanov approved these changes

2024-06-19 13:51 UTC, Kropanov commented
@Dmitriy8998 Let's Svetlana will test it out.

2024-06-19 13:56 UTC, Dmitriy8998 commented
I informed Svetlana when creating the commit

2024-06-20 06:35 UTC, sw1pr0g approved these changes

2024-06-20 08:35 UTC, Dmitriy8998 commented
Sveta was testing the program. For some reason, the value of  joints will not saved in her computer. I checked it in two browsers in my computer. The values are saved. I am attaching a video on the work. Please check from your computers. 
[Uploading Запись экрана от 20.06.2024 11:23:42.webm…]()

2024-06-20 10:37 UTC, Kropanov commented
> Sveta was testing the program. For some reason, the value of joints will not saved in her computer. I checked it in two browsers in my computer. The values are saved. I am attaching a video on the work. Please check from your computers. Uploading screen recording 20.06.2024 11:23:42.webm…

Is it working with publish...py file and without? Were you testing it?

2024-06-20 10:56 UTC, Dmitriy8998 commented
Im testing it without a file publish.py. With file publish.py values are not saved, although they are sent to the server.

2024-06-21 08:50 UTC, Dmitriy8998 commented
Fixed to file docer-compose.yml

2024-06-21 11:48 UTC, Kropanov approved these changes

2024-06-21 11:49 UTC, merged