fixed: Alignment position loaders and numeric valuse
sergei-nntu/orb pull request #140
Opened 2024-06-14 11:23 UTC by Dmitriy8998

2024-06-17 07:36 UTC, sw1pr0g requested changes
need to change naming of id/progress bars

2024-06-17 08:50 UTC, Dmitriy8998 commented
Created new commit with rework name id loader.

2024-06-17 10:24 UTC, sw1pr0g approved these changes

2024-06-17 12:18 UTC, Kropanov requested changes
![14 59 42](https://github.com/sergei-nntu/orb/assets/94756270/3965fd75-2234-429a-b17f-95355f77859f)
@Dmitriy8998 Need to align by right side as on the image above.

2024-06-18 08:18 UTC, Kropanov approved these changes

2024-06-18 08:18 UTC, merged