fix: enable  interface at first boot time and correct freez loader
sergei-nntu/orb pull request #144
Opened 2024-06-21 07:07 UTC by Dmitriy8998

Fixed bug in first loding and correct code. Correct loade freeze. Plase chek it.

2024-06-24 12:35 UTC, Kropanov requested changes

2024-06-24 12:35 UTC, Kropanov commented on web/src/utils/index.ts
> +// };
You should remove this unused code

2024-06-24 13:15 UTC, Dmitriy8998 commented on web/src/utils/index.ts
> +// };
Unused comments removed.

2024-06-25 06:44 UTC, sw1pr0g approved these changes

2024-06-26 16:33 UTC, Kropanov approved these changes

2024-06-28 13:37 UTC, Kropanov commented
Close without merging

2024-06-28 13:37 UTC, closed without merging